export default {
  '/merge-pdf': { title: 'Merge PDF Files Online Free | PDFBundles', desc: 'Merge PDF files online for free with PDFBundles. Combine multiple PDFs into one document quickly, no installation or sign up required.' },
  '/split-pdf': { title: 'Split PDF Files Online Free Tool | PDFBundles', desc: 'Split PDF files online for free with PDFBundles. Divide large documents into separate pages or sections in seconds, no signup needed.' },
  '/remove-pages': { title: 'Remove Pages From PDF Online | 100% Free | PDFBundles', desc: 'Remove pages from PDF files online for free with PDFBundles. Delete unwanted PDF pages and download the cleaned file in seconds.' },
  '/extract-pages': { title: 'Extract PDF Pages | Free PDF Tool', desc: 'Save specific pages as a new PDF. 100% free online tool.' },
  '/organize-pdf': { title: 'Organize PDF Pages Online Free | PDFBundles', desc: 'Organize PDF pages online for free with PDFBundles. Reorder PDF pages, rotate them, and download the updated file in seconds.' },
  '/scan-to-pdf': { title: 'Convert Scanned Images to PDF Free | PDFBundles', desc: 'Convert scanned images to PDF online for free with PDFBundles. Turn photos into a single PDF document and download it in seconds.' },
  '/compress-pdf': { title: 'Compress PDF Online Free | PDFBundles', desc: 'Compress PDF online for free with PDFBundles. Reduce PDF file size while keeping quality intact, no signup or software needed.' },
  '/repair-pdf': { title: 'Repair Corrupt PDF Files Free | PDFBundles', desc: 'Repair corrupt PDF files online for free with PDFBundles. Fix broken PDFs that won\'t open and download the working file in seconds.' },
  '/ocr-pdf': { title: 'OCR PDF Online Free | Make Scanned PDFs Searchable', desc: 'OCR PDF online for free with PDFBundles. Make scanned PDFs searchable and copy text directly from the document in seconds.' },
  '/jpg-to-pdf': { title: 'JPG to PDF Converter | Convert JPG Images to PDF', desc: 'Convert JPG to PDF online for free with PDFBundles. Combine JPG or PNG images into one PDF document and download it in seconds.' },
  '/word-to-pdf': { title: 'Convert Word to PDF Free | DOCX to PDF Converter', desc: 'Convert Word to PDF online for free with PDFBundles. Turn DOCX files into PDF documents and download them in seconds.' },
  '/ppt-to-pdf': { title: 'Convert PPT to PDF | PowerPoint to PDF converter', desc: 'Convert PPT to PDF online for free with PDFBundles. Turn PowerPoint presentations into PDF documents and download them in seconds.' },
  '/excel-to-pdf': { title: 'Convert Excel to PDF | XLSX to PDF converter Free', desc: 'Convert Excel to PDF online for free with PDFBundles. Turn XLSX spreadsheets into PDF documents and download them in seconds.' },
  '/html-to-pdf': { title: 'Convert HTML to PDF | Web Page to PDF Converter', desc: 'Convert HTML to PDF online for free with PDFBundles. Turn web pages into PDF documents and download them in seconds.' },
  '/pdf-to-png': { title: 'Convert PDF to PNG | PDF pages to PNG images', desc: 'Convert PDF to PNG online for free with PDFBundles. Turn PDF pages into PNG images and download them in seconds.' },
  '/pdf-to-word': { title: 'Convert PDF to Word Online Free | PDFBundles', desc: 'Convert PDF to Word online for free with PDFBundles. Turn PDF files into editable DOCX documents and download them in seconds.' },
  '/pdf-to-ppt': { title: 'Convert PDF to PPT | Free Online Converter', desc: 'Export PDF pages into slides. 100% free online converter.' },
  '/pdf-to-excel': { title: 'Convert PDF to Excel | Free Online Converter', desc: 'Extract PDF tables into Excel. 100% free online converter.' },
  '/rotate-pdf': { title: 'Rotate PDF Online | Free PDF Tool', desc: 'Rotate portrait/landscape pages. 100% free online tool.' },
  '/page-numbers': { title: 'Add Page Numbers to PDF | Free PDF Tool', desc: 'Draw page numbers on margins. 100% free online tool.' },
  '/add-watermark': { title: 'Add Watermark to PDF | Free PDF Tool', desc: 'Stamp customized text overlays. 100% free online tool.' },
  '/crop-pdf': { title: 'Crop PDF Online | Free PDF Tool', desc: 'Visual page dimensions cropper. 100% free online tool.' },
  '/edit-pdf': { title: 'Edit PDF Online | Free PDF Editor', desc: 'Add text, shapes, or notes to your PDF. 100% free online PDF editor.' },
  '/pdf-forms': { title: 'Fill PDF Forms Online | Free PDF Tool', desc: 'Fill out interactive forms. 100% free online tool.' },
  '/protect-pdf': { title: 'Protect PDF Online | Free Security Tool', desc: 'Add passwords & encrypt files. 100% free online tool.' },
  '/unlock-pdf': { title: 'Unlock PDF Online | Free Security Tool', desc: 'Remove passwords & restrictions. 100% free online tool.' },
  '/sign-pdf': { title: 'Sign PDF Online | Free Signature Tool', desc: 'Draw signatures and stamp them. 100% free online tool.' },
  '/redact-pdf': { title: 'Redact PDF Online | Free Security Tool', desc: 'Blackout sensitive information. 100% free online tool.' },
  '/compare-pdf': { title: 'Compare PDF Online | Free PDF Tool', desc: 'Compare two PDFs side-by-side. 100% free online tool.' },
  '/ai-pdf-assistant': { title: 'AI PDF Assistant | Free PDF Tool', desc: 'Chat, translate, or summarize PDFs using AI. 100% free online tool.' },
  '/background-remover': { title: 'Background Remover | Free AI Tool', desc: 'Remove background from images. 100% free online tool.' },
  '/image-upscaler': { title: 'Image Upscaler | Free AI Tool', desc: 'Enhance resolution and quality. 100% free online tool.' }
};
