export default {
  '/merge-pdf': { title: "Merge PDF Files Online Free | PDFBundles", desc: "Merge PDF files online for free with PDFBundles. Combine multiple PDFs into one document quickly, no installation or sign up required." },
  '/split-pdf': { title: "Split PDF Files Online Free Tool | PDFBundles", desc: "Split PDF files online for free with PDFBundles. Divide large documents into separate pages or sections in seconds, no signup needed." },
  '/remove-pages': { title: "Remove pages From PDF Online | 100% Free | PDFBundles", desc: "Remove pages from PDF files online for free with PDFBundles. Delete unwanted PDF pages and download the cleaned file in seconds." },
  '/extract-pages': { title: 'Extract Pages From PDF Online Free | PDFBundles', desc: 'Extract pages from PDF files online for free with PDFBundles. Pull pages from PDF documents and download them as a new file in seconds.' },
  '/organize-pdf': { title: "Organize PDF Pages Online Free | PDFBundles", desc: "Organize PDF pages online for free with PDFBundles. Reorder PDF pages, rotate them, and download the updated file in seconds." },
  '/scan-to-pdf': { title: "Convert Scanned Images to PDF Free | PDFBundles", desc: "Convert scanned images to PDF online for free with PDFBundles. Turn photos into a single PDF document and download it in seconds." },
  '/compress-pdf': { title: "Compress PDF Online Free | PDFBundles", desc: "Compress PDF online for free with PDFBundles. Reduce PDF file size while keeping quality intact, no signup or software needed." },
  '/repair-pdf': { title: "Repair Corrupt PDF Files Free | PDFBundles", desc: "Repair corrupt PDF files online for free with PDFBundles. Fix broken PDFs that won't open and download the working file in seconds." },
  '/ocr-pdf': { title: "OCR PDF Online Free | Make Scanned PDFs Searchable", desc: "OCR PDF online for free with PDFBundles. Make scanned PDFs searchable and copy text directly from the document in seconds." },
  '/jpg-to-pdf': { title: 'JPG to PDF Converter | Convert JPG Images to PDF', desc: 'Convert JPG to PDF online for free with PDFBundles. Combine JPG or PNG images into one PDF document and download it in seconds.' },
  '/word-to-pdf': { title: 'Convert Word to PDF Free | DOCX to PDF Converter', desc: 'Convert Word to PDF online for free with PDFBundles. Turn DOCX files into PDF documents and download them in seconds.' },
  '/ppt-to-pdf': { title: 'Convert PPT to PDF | PowerPoint to PDF converter', desc: 'Convert PPT to PDF online for free with PDFBundles. Turn PowerPoint presentations into PDF documents and download them in seconds.' },
  '/excel-to-pdf': { title: 'Convert Excel to PDF | XLSX to PDF converter Free', desc: 'Convert Excel to PDF online for free with PDFBundles. Turn XLSX spreadsheets into PDF documents and download them in seconds.' },
  '/html-to-pdf': { title: 'Convert HTML to PDF | Web Page to PDF Converter', desc: 'Convert HTML to PDF online for free with PDFBundles. Turn web pages into PDF documents and download them in seconds.' },
  '/pdf-to-png': { title: 'Convert PDF to PNG | PDF pages to PNG images', desc: 'Convert PDF to PNG online for free with PDFBundles. Turn PDF pages into PNG images and download them in seconds.' },
  '/pdf-to-word': { title: 'Convert PDF to Word Online Free | PDFBundles', desc: 'Convert PDF to Word online for free with PDFBundles. Turn PDF files into editable DOCX documents and download them in seconds.' },
  '/pdf-to-ppt': { title: 'Convert PDF to PPT Free | PDF to PowerPoint Converter', desc: 'Convert PDF to PPT online for free with PDFBundles. Turn PDF pages into editable PowerPoint slides and download them in seconds.' },
  '/pdf-to-excel': { title: 'Convert PDF to Excel Free | PDF Tables to Excel', desc: 'Convert PDF to Excel online for free with PDFBundles. Turn PDF tables into editable XLSX spreadsheets and download them in seconds.' },
  '/rotate-pdf': { title: 'Free Rotate PDF Online | Fix PDF Page Orientation', desc: 'Rotate PDF online for free with PDFBundles. Fix sideways or upside down PDF pages and download the corrected file in seconds.' },
  '/page-numbers': { title: 'Add PAge Number to PDF | Insert PDF Page Numbering', desc: 'Add page numbers to PDF online for free with PDFBundles. Insert PDF page numbering in any position and download the file in seconds.' },
  '/add-watermark': { title: 'Add Watermark to PDF | Stamp Text on PDF', desc: 'Add a watermark to PDF online for free with PDFBundles. Stamp text or a logo onto your PDF and download the file in seconds.' },
  '/crop-pdf': { title: 'Crop PDF Online | Trim PDF Page Margins', desc: 'Crop PDF online for free with PDFBundles. Trim PDF page margins visually and download the resized file in seconds.' },
  '/edit-pdf': { title: 'Edit PDF Online | Add text to PDF Free', desc: 'Edit PDF online for free with PDFBundles. Add text and annotations to your PDF and download the updated file in seconds.' },
  '/pdf-forms': { title: 'Fill PDF Forms Online | Free PDF Tool', desc: 'Fill out interactive forms. 100% free online tool.' },
  '/protect-pdf': { title: 'Protect PDF With Password | Encrypt PDF Files', desc: 'Protect PDF with a password online for free with PDFBundles. Encrypt PDF files and download the secured document in seconds.' },
  '/unlock-pdf': { title: 'Unlock PDF Online | Remove PDF Password Protection', desc: 'Unlock PDF online for free with PDFBundles. Remove PDF password protection and download the unlocked file in seconds.' },
  '/sign-pdf': { title: 'Sign PDF Online | Add Electronic Signature to PDF', desc: 'Sign PDF online for free with PDFBundles. Add an electronic signature to your document and download the signed file in seconds.' },
  '/redact-pdf': { title: 'Redact PDF Online | Black Out Sensitive Information PDF', desc: 'Redact PDF online for free with PDFBundles. Black out sensitive information permanently and download the secured file in seconds.' },
  '/compare-pdf': { title: 'Compare PDF Online | Find Differences Between 2 PDFs', desc: 'Compare PDF online for free with PDFBundles. See side by side differences between two PDF documents in seconds.' },
  '/ai-pdf-assistant': { title: 'AI PDF Assistant | Chat With PDF Using AI', desc: 'AI PDF assistant online for free with PDFBundles. Summarize, translate, and chat with your PDF documents in seconds.' },
  '/background-remover': { title: 'Remove Background From Image Free | Transparent Image Tool', desc: 'Remove background from image online for free with PDFBundles. Get a transparent background in seconds, no design skills needed.' },
  '/image-upscaler': { title: 'Upscale Images Online For Free | Increase Image Resolution', desc: 'Upscale images online for free with PDFBundles. Increase photo resolution and download the enhanced image in seconds.' }
};
