module.exports = {
  '/merge-pdf': { title: 'Merge PDF Online | Free PDF Converter Tool', desc: 'Combine multiple PDFs into one. 100% free online PDF merger with no signup required.' },
  '/split-pdf': { title: 'Split PDF Online | Free PDF Extractor Tool', desc: 'Extract ranges or split all pages. 100% free online PDF splitter.' },
  '/remove-pages': { title: 'Remove Pages from PDF | Free PDF Tool', desc: 'Delete pages from your PDF file. 100% free online tool.' },
  '/extract-pages': { title: 'Extract PDF Pages | Free PDF Tool', desc: 'Save specific pages as a new PDF. 100% free online tool.' },
  '/organize-pdf': { title: 'Organize PDF Pages | Free PDF Tool', desc: 'Drag and reorder page positions. 100% free online tool.' },
  '/scan-to-pdf': { title: 'Scan to PDF | Free PDF Tool', desc: 'Compile camera snapshots to PDF. 100% free online tool.' },
  '/compress-pdf': { title: 'Compress PDF Online | Free PDF Optimizer', desc: 'Reduce PDF file size on the server. 100% free online tool.' },
  '/repair-pdf': { title: 'Repair PDF Online | Free PDF Tool', desc: 'Fix corrupt PDF files & headers. 100% free online tool.' },
  '/ocr-pdf': { title: 'OCR PDF Online | Free Text Extractor', desc: 'Make scanned PDFs text-searchable. 100% free online tool.' },
  '/jpg-to-pdf': { title: 'Convert JPG to PDF | Free Online Converter', desc: 'Convert JPG/PNG images to PDF. 100% free online converter.' },
  '/word-to-pdf': { title: 'Convert Word to PDF | Free Online Converter', desc: 'Convert DOCX files to PDF. 100% free online converter.' },
  '/ppt-to-pdf': { title: 'Convert PPT to PDF | Free Online Converter', desc: 'Convert PPTX presentations to PDF. 100% free online converter.' },
  '/excel-to-pdf': { title: 'Convert Excel to PDF | Free Online Converter', desc: 'Convert XLSX sheets to PDF. 100% free online converter.' },
  '/html-to-pdf': { title: 'Convert HTML to PDF | Free Online Converter', desc: 'Convert web pages/code to PDF. 100% free online converter.' },
  '/pdf-to-png': { title: 'Convert PDF to PNG | Free Online Converter', desc: 'Extract PDF pages as PNG images. 100% free online converter.' },
  '/pdf-to-word': { title: 'Convert PDF to Word | Free Online Converter', desc: 'Extract PDF contents to DOCX. 100% free online converter.' },
  '/pdf-to-ppt': { title: 'Convert PDF to PPT | Free Online Converter', desc: 'Export PDF pages into slides. 100% free online converter.' },
  '/pdf-to-excel': { title: 'Convert PDF to Excel | Free Online Converter', desc: 'Extract PDF tables into Excel. 100% free online converter.' },
  '/rotate-pdf': { title: 'Rotate PDF Online | Free PDF Tool', desc: 'Rotate portrait/landscape pages. 100% free online tool.' },
  '/page-numbers': { title: 'Add Page Numbers to PDF | Free PDF Tool', desc: 'Draw page numbers on margins. 100% free online tool.' },
  '/add-watermark': { title: 'Add Watermark to PDF | Free PDF Tool', desc: 'Stamp customized text overlays. 100% free online tool.' },
  '/crop-pdf': { title: 'Crop PDF Online | Free PDF Tool', desc: 'Visual page dimensions cropper. 100% free online tool.' },
  '/edit-pdf': { title: 'Edit PDF Online | Free PDF Editor', desc: 'Add text, shapes, or notes to your PDF. 100% free online PDF editor.' },
  '/pdf-forms': { title: 'Fill PDF Forms Online | Free PDF Tool', desc: 'Fill out interactive forms. 100% free online tool.' },
  '/protect-pdf': { title: 'Protect PDF Online | Free Security Tool', desc: 'Add passwords & encrypt files. 100% free online tool.' },
  '/unlock-pdf': { title: 'Unlock PDF Online | Free Security Tool', desc: 'Remove passwords & restrictions. 100% free online tool.' },
  '/sign-pdf': { title: 'Sign PDF Online | Free Signature Tool', desc: 'Draw signatures and stamp them. 100% free online tool.' },
  '/redact-pdf': { title: 'Redact PDF Online | Free Security Tool', desc: 'Blackout sensitive information. 100% free online tool.' },
  '/compare-pdf': { title: 'Compare PDF Online | Free PDF Tool', desc: 'Compare two PDFs side-by-side. 100% free online tool.' },
  '/ai-pdf-assistant': { title: 'AI PDF Assistant | Free PDF Tool', desc: 'Chat, translate, or summarize PDFs using AI. 100% free online tool.' },
  '/background-remover': { title: 'Background Remover | Free AI Tool', desc: 'Remove background from images. 100% free online tool.' },
  '/image-upscaler': { title: 'Image Upscaler | Free AI Tool', desc: 'Enhance resolution and quality. 100% free online tool.' }
};
